# Site
name: Jonathan Kuhlman
description: ....
meta_description: ....
logo: /assets/images/logo.png
favicon: /assets/images/favicon.ico
paginate: 6
baseurl:
email: 'airmanjk03@gmail.com'
google_analytics: 
disqus:
sharethis:

# Authors
authors:
  john:
    name: LJ
    display_name: Jonathan Kuhlman
    image: /assets/images/swissalps.jpg
    email: airmanjk03@gmail.com
    web: https://ljkuhlman.github.io/Ultra/
    twitter:
    description: Hi, I am LJ.

# Plugins
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-seo-tag

permalinks: pretty

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: 'category/:name/'

# Other
markdown: kramdown
highlighter: rouge

# SEO
twitter:
  username: john
  card: summary

facebook:
  app_id:
  publisher: john.com
  admins:

social:
name: John Doe
links:
    - https://twitter.com/
    - https://www.facebook.com/
    - https://www.linkedin.com/
    - https://github.com/
